### ISSUE TITLE
swagger3.0 not working for autofocus

### ISSUE THREAD

**Issue by WAvdBeek** [smart-data-models/dataModel.OCF#1]
https://swagger.lab.fiware.org/?url=https://smart-data-models.github.io/dataModel.OCF/AutoFocus/swagger.yaml
gives the following error:
{"schemaValidationMessages":[{"level":"error","message":"Unable to read content.  It may be invalid JSON or YAML"}]}

**Comment by albertoabellagarcia** [comment]
checking...

**Comment by albertoabellagarcia** [comment]
It was an issue with quotes, that we have to manage to avoid the same issue when doing the other adaptations.
Now it works

**Comment by WAvdBeek** [comment]
Thanks! 
everything looks good
